### ISSUE TITLE
Possible leak detected

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-entity#11] opened 2016-05-10 11:45 UTC
Tests failing with Node@6 due to a possible leak with 'Reflect' #10 https://travis-ci.org/senecajs/seneca-entity/builds/129074838

**Comment by m1ome** [comment] 2016-05-15 14:21
@shanel262 seneca currently not support Node 6 IMO.

**Comment by m1ome** [comment] 2016-05-15 14:22
@shanel262 also you can look upon #9, it's kinda deprecated module

**Comment by mihaidma** [comment] 2016-05-15 15:10
the Node 6 issue is caused by the Lab tests, see this: https://github.com/hapijs/lab/issues/581
Found a solution on how to solve this.
Seneca and plugins are Node 6 compatible.

**Comment by m1ome** [comment] 2016-05-15 15:42
@mihaidma yeah but this repo is kinda deprecated module.

**Comment by mcdonnelldean** [comment] 2016-05-16 08:48
@m1ome Hey so this one shouldn't be marked as deprecated. I've closed that issue. @shanel262 @mihaidma My understanding is this is the correct repo for entitys. Can we confirm?

**Comment by shanel262** [comment] 2016-05-16 08:50
@mcdonnelldean Yeah this is the correct repo, I'm implementing a fix for Node 6 right now

**Comment by mcdonnelldean** [comment] 2016-05-16 08:56
@shanel262 Awesome stuff. @m1ome we had a issue with Lab causing failures but we were given a work around by the Lab team. Seneca should be compatible with Node 6 (although I hear there are general Node 6 regressions appearing across the node ecosystem so there may be issues yet).

**Closed by mcdonnelldean** 2016-05-16 08:56 UTC
